### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 7suxx** [sbidy/MacroMilter#10]
21.12.16 17:31:56 [2190] - Attachment with matching file extension found: Mail - Solvay.doc
21.12.16 17:31:56 [2190] - VBA no Macros found in file
21.12.16 17:33:45 [2195] - Unexpected error - fall back to ACCEPT: <type 'exceptions.AttributeError'> macromilter.py 192
21.12.16 17:39:27 [2213] - Unexpected error - fall back to ACCEPT: <type 'exceptions.AttributeError'> macromilter.py 192

**Comment by sbidy** [comment]
At this time I do some rework of the code and looking forward to release the V3 macro-milter with the enhancements from the olevba-tool project.

The (parsing) error will be fixed in the new version.

**Comment by sbidy** [comment]
Fixed with V3
