### ISSUE TITLE
FHS conformance?

### ISSUE THREAD

**Issue by robert-scheck** [sbidy/MacroMilter#13]
I am currently evaluating packaging of MacroMilter, which lead me to a lack of FHS conformance: Both, the executable and the configuration file are currently suggested to be installed in `/etc/macromilter/`.

FHS suggests to have e.g. `/usr/bin/macromilter` and `/etc/macromilter/config.ini`. However, the `macromilter.py` by default only searches in the same directory. While I indeed could patch this easily downstream, I wonder if it makes sense to change this upstream. I also understand that just changing might break existing setups, so it could be clever to first lookup `/etc/macromilter/config.ini` (FHS conform) and only if it does not exist search in the same directory like the `macromilter.py` is residing in for a `config.ini`.

**Comment by sbidy** [comment]
Updated the milter and the service to fulfill the conformance. It supports both possible configurations.
