### ISSUE TITLE
Logrotate and logging.handlers.TimedRotatingFileHandler()

### ISSUE THREAD

**Issue by robert-scheck** [sbidy/MacroMilter#17]
Code uses Python's `logging.handlers.TimedRotatingFileHandler()` and there is also a logrotate configuration file. May I ask why logrotation happens twice?

**Comment by sbidy** [comment]
I'll fix the "duplication" in the next release. I think we should switch to the logrotate approach for better handling and configuration capabilities.

**Comment by robert-scheck** [comment]
Fix verified as per 3.4.3
