### ISSUE TITLE
Error in macromilter.logrotate - ubuntu

### ISSUE THREAD

**Issue by sbidy** [sbidy/MacroMilter#21]
Error if logrotate script used with ubuntu:
```
logrotate_script: 2: logrotate_script: systemctl: not found
error: error running shared postrotate script for '/var/log/macromilter/macromilter.log'
```
and 
```
sysctl: cannot stat /proc/sys/try-restart: No such file or directory
sysctl: cannot stat /proc/sys/macromilter/service: No such file or directory
error: error running shared postrotate script for '/var/log/macromilter/macromilter.log'
```

**Comment by robert-scheck** [comment]
Which version of Ubuntu is that? No `systemctl` sounds like an older Ubuntu. The second with `sysctl` is definately wrong. Does Ubuntu ship `service` by default? Then this could be likely used as wrapper for all, SysVinit, upstart and systemd.

**Comment by sbidy** [comment]
It is a (old) 14.04.1 Ubuntu and yes `service` is a default package.
But I can't simply replace the `systemctl` with `service`.

Can we switch to a systemd command because it is more independent to distributions I guess?

**Comment by robert-scheck** [comment]
* `service` is historically a wrapper for SysVinit scripts, but can also handle systemd unit files (at least at Fedora and RHEL, to be tested for other distributions)
  * `systemctl` is the standard command line tool for systemd unit files
  * `sysctl` has _nothing_ to do with init stuff

Not sure how it is for Ubuntu, but in Fedora and RHEL, the following works as expected transparently:
```
$ service macromilter restart
Redirecting to /bin/systemctl restart macromilter.service
$ 
```

**Comment by sbidy** [comment]
I changed the postrotate command to `service macromilter restart`.
Now it should work on Ubuntu/Debian and Fed./RHEL.
