### ISSUE TITLE
Reject due to nested ZIP file leads to sub-optimal reject message

### ISSUE THREAD

**Issue by robert-scheck** [sbidy/MacroMilter#29]
Since 7d018efeb the reject message is not always perfect: If there is a nested ZIP file where the max. nesting limit is reached, the reject message still claims a suspicious VBA macro, even this check was never run; not sure if this is worth a fix.

**Comment by sbidy** [comment]
Implemented and now in testing - reject message hard coded. Maybe later moved to the config for customization purposes
