### ISSUE TITLE
Add new option to allow tagging rather rejecting (or replacing)

### ISSUE THREAD

**Issue by robert-scheck** [sbidy/MacroMilter#41]
I received an e-mail where a user kindly asks for a new option to allow tagging rather rejecting. This means, all e-mails shall be passed/accepted however a new header shall be inserted reflecting the MacroMilter result/status.

**Comment by sbidy** [comment]
I don't create a additional configuration option for that. The headers always created and added to the mail. If the sender/macro is whitelisted or the mail is relayed.
