### ISSUE TITLE
Install script not working for newer Debian versions

### ISSUE THREAD

**Issue by katschingg** [sbidy/MacroMilter#49]
The install_ubuntu.sh script is unfortunately not working for debian (stretch).
The command "initctl reload-configuration" doesn't work.
And I think "service MacroMilter start" is also not working.

**Comment by sbidy** [comment]
Can you please post the error message or an log trace of this behavior? Thanks!

**Comment by katschingg** [comment]
install_ubuntu.sh:30
> srv|root@/etc/logrotate.d$ initctl reload-configuration
> -bash: initctl: Kommando nicht gefunden.

install_ubuntu.sh:42
> srv|root@/etc/logrotate.d$ service MacroMilter start
> Failed to start MacroMilter.service: Unit MacroMilter.service not found.

**Comment by sbidy** [comment]
It seems to be that your debian has `upstart` not installed. The demon config and the install script works only with upstart-systems. I should update the doc..

**Comment by katschingg** [comment]
From the debian stretch release notes:

> Due to the lack of upstream maintainers, the Upstart init system has been removed from stretch. If your system relies on this package, you should note that it will not be updated during the lifetime of Debian 9, and starting from Debian 10 (buster), Upstart jobs may be removed from packages.
> 
> Please consider switching to a supported init system, like systemd or OpenRC.

**Comment by sbidy** [comment]
Ah, OK thank you!! I have to update the installation script to systemd rather than the documentation 😄 ...
Actually there are only a package for RHEL(Fedora, CentOS) or Suse systems available.

**Comment by sbidy** [comment]
The install script is updated with both sections.
- Ubuntu 12.04 ami-b08b6cd8: using upstart
- Ubuntu 14.04 ami-a427efcc: using upstart
- Ubuntu 14.10 and younger: using systemd

Please alter the script for the corresponding Ubuntu versions.
