### ISSUE TITLE
What about zip files?

### ISSUE THREAD

**Issue by heinrichheine** [sbidy/MacroMilter#5]
I installed the milter yesterday on my ubuntu server. It seems to work but only on files that are not inside a zip file. Is there a reason why you left this out?
Most of the "locky" like emails contain their crappy files inside zip container.

**Comment by sbidy** [comment]
I tested it with different macro types and files - also .zip:

```
Mar 22 22:21:22 sendemail[14344]: Setting content-type: text/plain
Mar 22 22:21:22 sendemail[14344]: DEBUG => Sending the attachment [**ebill0200442.zip**]
Mar 22 22:21:39 incela sendemail[14344]: ERROR => Received:     550 5.7.1 **ERROR = Attachment contains unallowed office macros!**
```

The oletools api can handle only un-encrypted zip files in this implementation.

Please check the "run.log" file for errors or stop the service and start the macromilter.py manual (python /etc/macomilter/macromilter.py) and provide me the log or std-out output.
Please check also the oletools version --> https://bitbucket.org/decalage/oletools/wiki/olevba 
My tested version is 0.42.

Thanks for your help!!

**Comment by heinrichheine** [comment]
I am using oletools 0.44.

I tested it with the attached doc file (came in as spam email). The doc is detected. 
`24.03.16 23:13:56 [4273] - Find Attachment with extension - File content type: application/msword - File name: rechnung_-postmaster 789.doc`
`24.03.16 23:13:56 [4273] - Attachment b949b42c7dab6883551f38de52428a08 already parsed ! REJECT`

I zipped the doc and tried again and the zip file is perfectly ignored by the milter with these log entries:
`24.03.16 23:09:28 [4269] - Find Attachment with extension - File content type: application/zip - File name: rechnung_-postmaster 789.doc.zip`
`24.03.16 23:09:28 [4269] - VBA no Macros found in file`
`24.03.16 23:09:28 [4269] - VBA parsing exit`

[rechnung_-postmaster 789.doc.zip](https://github.com/sbidy/MacroMilter/files/188774/rechnung_-postmaster.789.doc.zip)
![rechnung_-postmaster 789 doc](https://cloud.githubusercontent.com/assets/841989/14032829/db9c4d50-f215-11e5-8f94-3c847ee63154.png) - due to upload restrictions, i had to add the png extension to the doc file.

I checked the documentation of the olevba and i am not quite sure if olevba can handle ordinary zip files. The documentation is mentioning zip file support always together with zip-containers for office files (docx, etc).

**Comment by heinrichheine** [comment]
Just checked the source of olevba.py and found this text

``` python
def detect_vba_macros(self):
        """
        Detect the potential presence of VBA macros in the file, by checking
        if it contains VBA projects. Both OLE and OpenXML files are supported
```

So maybe the way to handle document files inside a zip will be to check if the attachment is a zip file and if so, iterate through all files inside the zip and push each to the vba parser.

**Comment by sbidy** [comment]
Yes you are right. The zip is not detected. I'll check this and maybe provide a fix or talk to Philippe.

**Comment by sbidy** [comment]
Ok, now I know why the zip file is not recognized by the milter!
An OLE Office file (legacy 97-2003 formats) in a zip is technically like a docm or xlsm (with vbaProject.bin inside). But if it's a zip with a docm or xml or mht inside, it won't work. It's better to unzip each file in memory, then scan them.

Now, I add in the next days a build-in in-memory unzip function to handle these files correctly.

Thank you for the report and tests!

**Comment by heinrichheine** [comment]
Great! Really looking for this. 
Things may to consider might be a file size limit to secure system performance and zips inside zipfiles.

**Comment by sbidy** [comment]
I added a "normal" zip extraction function to the milter.
The recursive and "rar" support is outstanding and I hope to add this in the next days.

I leave this issue open.

**Comment by heinrichheine** [comment]
Thank you very much. I will give it a try tomorrow!

Von meinem iPhone gesendet

**Comment by heinrichheine** [comment]
Is working!! Thank you

**Comment by sbidy** [comment]
Rar and recursive support is coming soon :smiley: (in V3).
