### ISSUE TITLE
Link to the second video is broken

### ISSUE THREAD

**Issue by yoshimo** [sbidy/MacroMilter#54]
If you follow the link to https://events.mi.hdm-stuttgart.de/2016-06-29-mi-pr%C3%A4sentationstag-ss16/MacroMilter%3A%20Malware-Filter%20f%C3%BCr%20E-Mails
You get PHP warnings.
Maybe you should mirror it somewhere else or help the university to fix their page.

**Comment by sbidy** [comment]
Thank you - I'll remove the link or look for another source.

**Comment by sbidy** [comment]
removed link ..
